package com.example.myapp.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WEATHER.
 */
public class Weather {

    private Long id;
    private String temperature;
    private String introduction;
    private String city;
    private java.util.Date date;

    public Weather() {
    }

    public Weather(Long id) {
        this.id = id;
    }

    public Weather(Long id, String temperature, String introduction, String city, java.util.Date date) {
        this.id = id;
        this.temperature = temperature;
        this.introduction = introduction;
        this.city = city;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTemperature() {
        return temperature;
    }

    public void setTemperature(String temperature) {
        this.temperature = temperature;
    }

    public String getIntroduction() {
        return introduction;
    }

    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
